arrowParens: always
bracketSpacing: true
importOrder: 
  - "^node:"
  - "^[^\\.](.+)$"
  - "^types@"
  - "^[\\.]"
importOrderCaseInsensitive: true
importOrderGroupNamespaceSpecifiers: true
importOrderSeparation: true
plugins: 
  - "@trivago/prettier-plugin-sort-imports"
printWidth: 80
semi: true
singleQuote: true
tabWidth: 4
trailingComma: none
useTabs: false